import type { InteractionSurfaceKind, SemanticContextKind } from "../domain/state/index.js";

export interface StateGuide { id: string; version: number; text: string; }

const guide = (id: string, text: string, version = 5): StateGuide => ({
  id: `re-p1-${id}-guide`,
  version,
  text
});

const COMBAT_BASELINE = [
  "Normal combat baseline unless current visible facts override it:",
  "a turn usually starts with 3 Energy and draws 5 cards;",
  "the hand limit is normally 10;",
  "unspent Energy normally expires and the next turn recalculates Energy;",
  "Block prevents ordinary damage before HP loss and normally clears at the start of the next turn;",
  "played Attacks and Skills normally go to the Discard Pile, Powers normally remain active, and unplayed cards normally discard at end of turn;",
  "Retain keeps a card in hand, Ethereal Exhausts it at end of turn, and Exhaust removes it for the rest of combat;",
  "when a draw cannot be completed from the Draw Pile, the Discard Pile is normally shuffled into a new Draw Pile;",
  "Potions normally cost no Energy and do not count as playing cards;",
  "enemy intents reveal the next enemy actions.",
  "Exact visible card, relic, potion, power, status, character, enemy, and guide text always has priority over these defaults."
].join(" ");

/** Context guides explain game meaning and one local strategic lens; surface guides explain the immediate protocol. */
export const CONTEXT_GUIDES: Record<SemanticContextKind, StateGuide> = {
  combat: guide("context-combat", `Semantic context is combat. ${COMBAT_BASELINE} Use exact displayed values and statuses without inventing or double-applying modifiers. Preserve HP by checking safe lethal, total visible incoming damage, Block and mitigation, threat removal, card order, Energy, hand space, draw/discard/exhaust cycles, potions, and whether immediate defense or scaling produces the best full-turn result.`),
  reward_flow: guide("context-reward-flow", "Semantic context is a reward flow. Resolve the active child surface using exact visible rewards and inventory limits. Take value that improves the run, but compare optional cards with skip, manage potion capacity explicitly, and do not interpret every separately labeled alternative as skip."),
  card_reward: guide("context-card-reward", "Semantic context is a card reward. Compare every visible card with skip. A card should solve a real need, improve synergy or consistency, or add sufficient power to justify making future draws less concentrated; rarity and availability alone are not reasons to take it."),
  rewards: guide("context-rewards", "Semantic context is a post-combat rewards screen. Claim useful visible gold, relic, potion, or card value, resolve child reward surfaces, and manage full inventory deliberately. Do not proceed while meaningful advertised value remains unresolved."),
  map: guide("context-map", "Semantic context is map navigation. Choose among visible connected nodes while planning toward the known Act boss. Treat HP, potions, gold, deck strength, and route flexibility as resources; balance safer rooms against elites, shops, rest sites, and other growth without inventing hidden rooms or future outcomes."),
  rest: guide("context-rest", "Semantic context is a rest site. Rest normally heals 30% of max HP and Smith normally upgrades one card, but visible options and effects are authoritative. Compare the survival value of healing with the repeated value of an upgrade or another enabled option; do not use a fixed HP threshold."),
  event: guide("context-event", "Semantic context is an event. Evaluate only currently revealed text, exact visible costs, rewards, HP changes, cards, relics, gold, and enabled choices. Do not use memorized or hidden future event outcomes; a new event may still be actionable when it exposes a known exact surface."),
  shop: guide("context-shop", "Semantic context is a shop. Gold spent now cannot fund later offers. Compare cards, relics, potions, and permanent card removal by current weakness, deck consistency, inventory capacity, price, remaining gold, and opportunity cost; affordability alone is insufficient."),
  treasure: guide("context-treasure", "Semantic context is treasure collection. Opening, choosing or skipping a visible reward, and leaving may be separate steps. Evaluate the exact relic or reward as permanent run value, respect inventory and child surfaces, and proceed only through advertised actions."),
  crystal_sphere: guide("context-crystal-sphere", "Semantic context is the Crystal Sphere. Preserve current support limits and use only exact visible facts; do not infer hidden predictions or actions."),
  menu: guide("context-menu", "Semantic context is a top-level menu. Continue the intended bounded ordinary run or enter supported single-player flow only through advertised actions."),
  run_ended: guide("context-run-ended", "The bounded run has ended. Stop before choosing any restart action."),
  combat_transition: guide("context-combat-transition", "Combat is starting or resolving. No player input owner exists; poll only and do not reason about a decision until a coherent combat surface appears."),
  run_transition: guide("context-run-transition", "A standard run has committed and its first player-visible state is still mounting. No input owner exists; poll only and do not infer future actions."),
  unknown: guide("context-unknown", "The semantic origin is unknown. Only a separately supported exact surface may be actionable; never infer missing game facts or strategy from the unknown context.")
};

export const SURFACE_GUIDES: Record<InteractionSurfaceKind, StateGuide> = {
  human_ui: guide("surface-human-ui", "Active surface is the exact current human-reachable UI. Treat facts, entities and controls as player-visible C evidence; choose exactly one advertised opaque affordance. A owns flow interpretation, including whether selection, confirm, cancel, close or successor observation is the right next step. Never invent a control, target, hidden outcome or business completion."),
  combat_turn: guide("surface-combat-turn", "Active surface is a combat turn. First check exact safe lethal. Otherwise compare the complete turn: visible enemy intents and total incoming damage, Block and mitigation, threat priority, card and potion order, Energy, hand limit, draw/discard/exhaust state, powers, and scaling. Preserve HP when the prevention is worth more than the lost offense, but accept bounded damage when it secures a stronger total outcome. Unspent Energy normally expires, yet never play a harmful or low-value card merely to spend it. Use exact displayed values and choose one advertised card, potion, or end-turn action; targets and operands are already bound in the opaque action ID."),
  combat_pile_card_selection: guide("surface-combat-pile-card-selection", "Active surface is a source-bound combat-pile transaction, not a generic card picker. Read mutationKind, commitMode, source provenance, source and destination piles, replacement, position, overflow, exact card instances, selected membership, and bounds. Choose the card that best serves the exposed purpose and current combat plan. automatic_at_max commits at the native bound; manual_confirm requires a separate advertised confirm and may permit zero selections. Source names are provenance, not client authority; identical selector shapes do not imply identical business outcomes. Choose one opaque advertised action.", 8),
  combat_hand_card_selection: guide("surface-combat-hand-card-selection", "Active surface is an in-combat hand-card transaction. Read the exact purpose, card instance IDs, membership, replacement behavior, limits, stage, and confirm state. Choose for that purpose rather than by generic card strength; consider whether the selected card would otherwise be played, retained, discarded, or exhausted. Use one advertised action, and leave peek mode before selecting."),
  event_card_acquisition: guide("surface-event-card-acquisition", "Active surface is an audited event card acquisition. The visible cards are temporary offers and the required selected count will enter the persistent deck. Compare exact card facts with current needs, synergy, consistency, and deck dilution; do not select merely because cards are offered. Respect selected membership and choose one advertised select or deselect action."),
  generated_card_choice: guide("surface-generated-card-choice", "Active surface is a source-bound one-of-N temporary-card choice. Read purpose, sourceKind, destination, selectedCardCostPolicy, overflowDestination, canSkip, and exact current card text; do not infer semantics from the shared grid alone. Evaluate immediate combat value, Energy, hand space, target availability, and whether the card is added, played, or applied. The current contract is authoritative for source-specific cost and destination rules. Choose one advertised action, skip only when explicitly available and better, or leave peek mode before choosing.", 6),
  card_bundle_selection: guide("surface-card-bundle-selection", "Active surface is a two-stage choice between atomic card bundles. Compare each package as a whole by total deck impact and current needs; member cards are descriptive facts, not separate legal actions. Preview one advertised bundle, then confirm or cancel only through the exact actions exposed for that preview."),
  card_selection: guide("surface-card-selection", "Active surface is card selection. Read selectionMode, purpose, prompt, options, previewShowing, previewCards, and confirm/cancel availability. When purpose is visible, choose cards that best satisfy it; when key facts are absent, do not invent them. A visible preview describes the current confirm/cancel consequence. Choose exactly one immediate advertised action, and do not claim hidden selected membership or remaining capacity."),
  deck_enchant_selection: guide("surface-deck-enchant", "Active surface is a two-stage deck enchant selection. Read the exact enchantment, constraints, selected card instances, candidates, and stage. Prefer a legal target that gains meaningful value from the enchantment and remains useful in the current deck. Selecting, previewing, cancelling, and applying are distinct advertised actions."),
  deck_removal_selection: guide("surface-deck-removal", "Active surface is the merchant card-removal child. Read exact visible cards, limits, selected membership, prompt, and stage. Prefer removing a card that reduces consistency or no longer serves the current deck, without applying a universal ranking. This is not an immediate purchase: select, preview, confirm, or cancel only through advertised actions."),
  event_deck_removal_selection: guide("surface-event-deck-removal", "Active surface is the exact Luminous Choir two-card removal transaction. Compare exact visible deck instances and remove two cards whose loss best improves consistency while accounting for the advertised Spore Mind addition. Selection, preview return, and final commit are distinct; commit is complete only after both cards are absent, Spore Mind is added, and the event finishes."),
  relic_deck_removal_selection: guide("surface-relic-deck-removal", "Active surface is the exact Precise Scissors acquisition child. It shares deck-removal mechanics but has no shop price or service semantics. Prefer a removal that improves current deck consistency, using exact visible facts, and select, preview, confirm, or cancel only through advertised actions."),
  reward_deck_removal_selection: guide("surface-reward-deck-removal", "Active surface is one exact CardRemovalReward child. It shares deck-removal mechanics but is not a merchant purchase or relic acquisition. Prefer a removal that improves current deck consistency, using exact visible facts, and select, preview, confirm, or cancel only through advertised actions."),
  deck_upgrade_selection: guide("surface-deck-upgrade", "Active surface is a purpose-specific deck upgrade selector. Compare current card facts with the exact visible upgraded preview, respect membership and limits, and prefer upgrades with strong immediate and repeated value for survival, damage, scaling, draw, energy, or consistency. Use only advertised select, cancel, or confirm actions; completion requires the selected instances to be upgraded."),
  deck_transform_selection: guide("surface-deck-transform", "Active surface is a purpose-specific random deck transformation. Treat the replacement as unknown unless visible. Select a weak or poorly fitting eligible card when that improves expected deck quality, without claiming the future replacement. Use only advertised selection, preview, presentation-toggle, cancel, or commit actions."),
  wood_carvings_replacement_selection: guide("surface-wood-carvings-replacement", "Active surface is the native Wood Carvings Bird or Torus replacement. The replacement card is deterministic and visible. Compare that exact replacement with eligible Basic cards and choose the swap that most improves current deck function, then use only advertised select, preview-cancel, or confirm actions."),
  card_reward_selection: guide("surface-card-reward-selection", "Active surface is a Bridge-authoritative card reward. Compare each visible card and every separately labeled alternative with skip or continue. Prefer a card only when its expected damage, defense, scaling, draw, Energy, consistency, or specific synergy outweighs deck dilution; rarity and position are insufficient. Choose one opaque advertised action."),
  card_reward: guide("surface-card-reward", "Active surface is card reward selection. Take a visible card only when it improves expected deck quality relative to the exact skip or continue alternative; every added card changes future draw frequency. Use only the advertised action."),
  reward_claim: guide("surface-reward-claim", "Active surface is the outer reward screen. Claim useful visible rewards, manage potion capacity through advertised discard or replacement actions, and proceed only after meaningful available value is resolved. Card rewards and other children open distinct surfaces; do not choose their contents here."),
  map_navigation: guide("surface-map-navigation", "Active surface is map navigation. Choose one currently selectable connected node on a route that the present HP, potions, deck, and gold can survive while gaining enough strength for the known Act boss. Balance immediate risk, elites, rest sites, shops, rewards, and later visible branching; never invent hidden rooms."),
  event_dialogue: guide("surface-event-dialogue", "Active surface is an Ancient event dialogue. Read only the revealed prefix ending at the current line; future dialogue is intentionally absent. Advance only through the single advertised action because it is the current legal interaction, not because of imagined future text."),
  event_option: guide("surface-event-option", "Active surface is a Bridge-authoritative event option protocol. Read event meaning from context and exact option text from surface. Compare visible costs and benefits against survival and long-term win probability, never hidden event knowledge, and choose only one advertised action."),
  rest_site: guide("surface-rest-site", "Active surface is a Bridge-authoritative rest site. Rest normally heals 30% of max HP and Smith normally upgrades one card, unless exact visible effects change the options. Heal when expected near-term survival risk outweighs permanent growth; otherwise prefer the enabled upgrade or other option with the best repeated value. Use visible facts, not a fixed HP percentage. A Smith choice may open a separate selector."),
  shop_inventory: guide("surface-shop-inventory", "Active surface is the merchant inventory. Compare typed cards, relics, potions, and permanent card removal using exact price, stock, eligibility, current weaknesses, deck consistency, potion slots, remaining gold, and the value of preserving gold for later. Do not buy merely because an item is affordable. Choose one advertised purchase or close action; a full potion belt prevents storing another potion unless an explicit replacement path exists, and removal opens a child selector."),
  shop_room: guide("surface-shop-room", "Active surface is the merchant room after inventory is closed. Reopen only when useful shopping remains; otherwise proceed to the map through an advertised action. Purchase actions cannot exist on this surface."),
  treasure_room: guide("surface-treasure-room", "Active surface is the ordinary single-player treasure room. Chest opening, visible relic choice or skip, child effects, and departure are separate advertised actions. Relics are permanent run modifiers, so evaluate exact visible effects and current build rather than rarity alone. Completion requires the corresponding semantic inventory or stage change."),
  game_over: guide("surface-game-over", "Active surface is the ordinary single-player game-over lifecycle. The intro Continue and later return control are separate advertised actions. Preserve the current visible stage, do not infer restart, and stop at the bounded run boundary."),
  character_select: guide("surface-character-select", "Active surface is ordinary single-player character selection. Compare only visible supported characters, the selected panel, Ascension controls, and advertised navigation or embark actions. Do not invent starting decks or hard-code a favorite character unless configuration explicitly requests one."),
  main_menu: guide("surface-main-menu", "Active surface is the exact root menu. Continue or open Single Player only through advertised opaque actions consistent with the bounded ordinary run. Other visible root choices marked unsupported are facts, not executable options."),
  singleplayer_menu: guide("surface-singleplayer-menu", "Active surface is the standard single-player submenu. Open Standard or go Back only through advertised actions. Daily and Custom remain visible but outside this bounded contract."),
  option_choice: guide("surface-option-choice", "Active surface is an indexed option choice. Compare only enabled options by exact visible costs, benefits, risks, and run impact. Choose the best advertised option, or proceed only when a distinct proceed action is exposed; never infer meaning from index or position alone."),
  shop_interaction: guide("surface-shop", "Active surface is compatibility shop interaction. Buy one listed affordable item only when it materially improves the run relative to leaving, and use only an allowed action."),
  treasure_claim: guide("surface-treasure", "Active surface is compatibility treasure claim. Prefer the useful exposed reward; otherwise continue only through an advertised action."),
  grid_interaction: guide("surface-grid", "Active surface is a grid interaction. Choose only an exposed tool, cell, or finish action and do not invent puzzle rules or hidden board state."),
  menu_choice: guide("surface-menu", "Active surface is a menu choice. Choose only a supported enabled option consistent with continuing the bounded ordinary run."),
  no_action: guide("surface-no-action", "There is no actionable interaction surface. Do not produce a decision or invoke the model."),
  unsupported: guide("surface-unsupported", "The active interaction protocol is unsupported. Do not produce a decision, infer an action, or invoke the model.")
};
