import type { InteractionSurfaceKind, SemanticContextKind } from "../domain/state/index.js";

export interface StateGuide { id: string; version: number; text: string; }

const guide = (id: string, text: string, version = 4): StateGuide => ({
  id: `re-p1-${id}-guide`,
  version,
  text
});

/** Context guides explain game meaning and one local strategic lens; surface guides explain the immediate protocol. */
export const CONTEXT_GUIDES: Record<SemanticContextKind, StateGuide> = {
  combat: guide("context-combat", "Semantic context is combat. context retains encounter, turn, enemy, intent, and resource facts even when an overlay is active. First consider safe lethal, visible incoming damage, threat removal, current resources, and whether immediate defense or scaling is needed."),
  reward_flow: guide("context-reward-flow", "Semantic context is a reward flow. Improve the run through the active reward surface, resolve visible inventory constraints, and do not assume every alternative means skip."),
  card_reward: guide("context-card-reward", "Semantic context is a card reward. Compare each card with skip using current deck needs, synergy, consistency, and dilution; rarity alone is not a reason to take a card."),
  rewards: guide("context-rewards", "Semantic context is a post-combat rewards screen. Claim useful visible value while respecting potion capacity and child reward surfaces; do not leave value accidentally."),
  map: guide("context-map", "Semantic context is map navigation and retains visible route facts. Balance survival and permanent growth toward the current Act boss using current HP, deck strength, elites, rest sites, shops, and visible route flexibility without inventing hidden rooms."),
  rest: guide("context-rest", "Semantic context is a rest site. Compare healing's survival value with upgrades or other visible growth options using current facts rather than one fixed HP threshold."),
  event: guide("context-event", "Semantic context is an event. Evaluate only exact visible costs, rewards, and consequences; a new event id is data when it exposes a known surface, and hidden or memorized outcomes must not be assumed."),
  shop: guide("context-shop", "Semantic context is a shop. Gold is limited: compare purchase or removal impact, current weaknesses, and opportunity cost; affordability alone is insufficient."),
  treasure: guide("context-treasure", "Semantic context is treasure collection. Evaluate exact visible reward facts and their current inventory effect; use skip or proceed only when exposed."),
  crystal_sphere: guide("context-crystal-sphere", "Semantic context is the Crystal Sphere. Preserve current support limits and use only exact visible facts; do not infer hidden predictions or actions."),
  menu: guide("context-menu", "Semantic context is a top-level menu. Continue the intended bounded ordinary run or enter supported single-player flow only through advertised actions."),
  run_ended: guide("context-run-ended", "The bounded run has ended. Stop before choosing any restart action."),
  combat_transition: guide("context-combat-transition", "Combat is starting or resolving. No player input owner exists; poll only and do not reason about a decision until a coherent combat surface appears."),
  run_transition: guide("context-run-transition", "A standard run has committed and its first player-visible state is still mounting. No input owner exists; poll only and do not infer future actions."),
  unknown: guide("context-unknown", "The semantic origin is unknown. Only a separately supported exact surface may be actionable; never infer missing game facts or strategy from the unknown context.")
};

export const SURFACE_GUIDES: Record<InteractionSurfaceKind, StateGuide> = {
  combat_turn: guide("surface-combat-turn", "Active surface is a combat turn. Check safe lethal first; otherwise sequence cards and potions to reduce expected incoming damage while advancing the fight. Consider target priority, energy, block, hand, powers, draw/discard/exhaust effects, usable potions, and whether ending turn leaves avoidable damage. Choose one immediate advertised card, potion, or end-turn action; targets and indices are encoded in opaque action ids, and do not play a card merely to spend energy."),
  combat_pile_card_selection: guide("surface-combat-pile-card-selection", "Active surface is a source-bound, structurally described combat-pile transaction. Read mutationKind, commitMode, source provenance, source and destination piles, replacement/position/overflow semantics, exact visible card instances, current selected set, and bounds. Choose the exact card that best serves the exposed purpose while respecting those semantics. automatic_at_max commits when the native bound is reached; manual_confirm requires a separate advertised confirm action and may allow zero selections. Source names are provenance, not client-side authority. Do not infer one source card's business outcome from another or from a familiar selector shape. Choose only one Bridge-advertised opaque action per decision.", 7),
  combat_hand_card_selection: guide("surface-combat-hand-card-selection", "Active surface is an in-combat hand-card selection. Read the exact source purpose, card instance ids, selected membership, mode, limits, and confirm state. Choose the card that best serves that purpose in the visible hand; the generally strongest card may be wrong for this transaction. Selecting another card may replace the current selection. Choose only one advertised action, and return from peek mode before selecting."),
  event_card_acquisition: guide("surface-event-card-acquisition", "Active surface is an audited event card acquisition. The visible cards are temporary offers and the fixed number selected will be added to the persistent run deck. Compare event meaning, exact card facts, current deck need, synergy, consistency, selection count, and membership; do not select merely because cards are offered. Choose only one advertised select or deselect action."),
  generated_card_choice: guide("surface-generated-card-choice", "Active surface is a source-bound one-of-N temporary-card choice. Read purpose, sourceKind, destination, selectedCardCostPolicy, overflowDestination, and canSkip instead of inferring business meaning from the shared grid. Evaluate offers for the immediate fight and exact destination/cost policy, preferring the option that best answers the current threat or combat plan. Quasar adds the chosen card at its shown cost; potion and Splash choices make it free this turn; Knowledge Demon applies the chosen effect immediately and cannot be skipped. The cards are offers, not current pile members. Choose one advertised action, use skip only when explicitly present and strategically preferable, or return from peek mode before choosing.", 5),
  card_bundle_selection: guide("surface-card-bundle-selection", "Active surface is a two-stage choice between atomic card bundles. Compare each package as a whole by total deck impact and current needs; member cards are descriptive facts, not separate legal actions. Preview one advertised bundle, then confirm or cancel only through the exact actions exposed for that preview."),
  card_selection: guide("surface-card-selection", "Active surface is card selection. Read selectionMode, purpose, prompt, options, previewShowing, previewCards, and confirm/cancel availability. When purpose is visible, choose cards that best satisfy it; when key facts are absent, do not invent them. A visible preview describes the current confirm/cancel consequence. Choose exactly one immediate advertised action, and do not claim hidden selected membership or remaining capacity."),
  deck_enchant_selection: guide("surface-deck-enchant", "Active surface is a two-stage deck enchant selection. Read the exact enchantment, constraints, selected card instances, candidates, and stage. Prefer a legal target that gains meaningful value from the enchantment and remains useful in the current deck. Selecting, previewing, cancelling, and applying are distinct advertised actions."),
  deck_removal_selection: guide("surface-deck-removal", "Active surface is the merchant card-removal child. Read exact visible cards, limits, selected membership, prompt, and stage. Prefer removing a card that reduces consistency or no longer serves the current deck, without applying a universal ranking. This is not an immediate purchase: select, preview, confirm, or cancel only through advertised actions."),
  relic_deck_removal_selection: guide("surface-relic-deck-removal", "Active surface is the exact Precise Scissors acquisition child. It shares deck-removal mechanics but has no shop price or service semantics. Prefer a removal that improves current deck consistency, using exact visible facts, and select, preview, confirm, or cancel only through advertised actions."),
  reward_deck_removal_selection: guide("surface-reward-deck-removal", "Active surface is one exact CardRemovalReward child. It shares deck-removal mechanics but is not a merchant purchase or relic acquisition. Prefer a removal that improves current deck consistency, using exact visible facts, and select, preview, confirm, or cancel only through advertised actions."),
  deck_upgrade_selection: guide("surface-deck-upgrade", "Active surface is a purpose-specific deck upgrade selector. Compare current card facts with the exact visible upgraded preview, respect membership and limits, and prefer upgrades with strong immediate and repeated value for survival, damage, scaling, draw, energy, or consistency. Use only advertised select, cancel, or confirm actions; completion requires the selected instances to be upgraded."),
  deck_transform_selection: guide("surface-deck-transform", "Active surface is a purpose-specific random deck transformation. Treat the replacement as unknown unless visible. Select a weak or poorly fitting eligible card when that improves expected deck quality, without claiming the future replacement. Use only advertised selection, preview, presentation-toggle, cancel, or commit actions."),
  wood_carvings_replacement_selection: guide("surface-wood-carvings-replacement", "Active surface is the native Wood Carvings Bird or Torus replacement. The replacement card is deterministic and visible. Compare that exact replacement with eligible Basic cards and choose the swap that most improves current deck function, then use only advertised select, preview-cancel, or confirm actions."),
  card_reward_selection: guide("surface-card-reward-selection", "Active surface is a Bridge-authoritative card reward selection. Compare visible cards and every separately labeled alternative against current deck needs; skip can be correct and rarity alone is insufficient. Choose only an advertised opaque action and never reinterpret an alternative as skip from its position."),
  card_reward: guide("surface-card-reward", "Active surface is card reward selection. Take a card only when it improves expected deck quality relative to skip or continue, and use only the exact advertised action."),
  reward_claim: guide("surface-reward-claim", "Active surface is a Bridge-authoritative outer reward screen. Claim meaningful visible value, handle potion capacity deliberately through advertised discard actions, and proceed only after useful available rewards are resolved. A card reward opens a distinct child surface; do not assume its choices here."),
  map_navigation: guide("surface-map-navigation", "Active surface is map navigation. Choose one currently selectable next node on a route the current HP and deck can survive while still gaining enough growth for the Act boss. Balance elites, rest sites, shops, and visible route flexibility without inventing hidden rooms."),
  event_dialogue: guide("surface-event-dialogue", "Active surface is an Ancient event dialogue. Read only the revealed prefix ending at the current line; future dialogue is intentionally absent. Advance only through the single advertised action because it is the current legal interaction, not because of imagined future text."),
  event_option: guide("surface-event-option", "Active surface is a Bridge-authoritative event option protocol. Read event meaning from context and exact option text from surface. Compare visible costs and benefits against survival and long-term win probability, never hidden event knowledge, and choose only one advertised action."),
  rest_site: guide("surface-rest-site", "Active surface is a Bridge-authoritative rest site. Compare each enabled visible option. Choose healing when survival risk materially threatens the run; choose Smith or another growth option when the current margin is adequate and the gain is meaningful. Use exact visible facts rather than a fixed HP percentage. A Smith choice may open a separate selector; proceeding is a distinct action."),
  shop_inventory: guide("surface-shop-inventory", "Active surface is the open merchant inventory. Compare typed card, relic, potion, and removal offers using price, stock, visibility, eligibility, current weaknesses, inventory limits, remaining gold, and opportunity cost. Do not buy merely because an offer is affordable. Choose only an advertised purchase or close action; a full potion belt blocks potion purchase and removal opens a child selector."),
  shop_room: guide("surface-shop-room", "Active surface is the merchant room after inventory is closed. Reopen only when useful shopping remains; otherwise proceed to the map through an advertised action. Purchase actions cannot exist on this surface."),
  treasure_room: guide("surface-treasure-room", "Active surface is the single-player treasure room. Chest opening, relic choice or skip, and departure are separate advertised actions. Relics are permanent growth, but evaluate the exact visible effect and current build; completion requires the semantic inventory post-state."),
  game_over: guide("surface-game-over", "Active surface is the ordinary single-player game-over lifecycle. The intro Continue and later return control are separate advertised actions. Preserve the current visible stage, do not infer restart, and stop at the bounded run boundary."),
  character_select: guide("surface-character-select", "Active surface is ordinary single-player character selection. Compare only visible supported characters, the selected panel, Ascension controls, and advertised navigation or embark actions. Do not invent starting decks or hard-code a favorite character unless configuration explicitly requests one."),
  main_menu: guide("surface-main-menu", "Active surface is the exact root menu. Continue or open Single Player only through advertised opaque actions consistent with the bounded ordinary run. Other visible root choices marked unsupported are facts, not executable options."),
  singleplayer_menu: guide("surface-singleplayer-menu", "Active surface is the standard single-player submenu. Open Standard or go Back only through advertised actions. Daily and Custom remain visible but outside this bounded contract."),
  option_choice: guide("surface-option-choice", "Active surface is an indexed option choice. Choose the enabled option with the best exact visible trade-off, or use an explicit proceed action only when advertised."),
  shop_interaction: guide("surface-shop", "Active surface is compatibility shop interaction. Buy one listed affordable item only when it materially improves the run relative to leaving, and use only an allowed action."),
  treasure_claim: guide("surface-treasure", "Active surface is compatibility treasure claim. Prefer the useful exposed reward; otherwise continue only through an advertised action."),
  grid_interaction: guide("surface-grid", "Active surface is a grid interaction. Choose only an exposed tool, cell, or finish action and do not invent puzzle rules or hidden board state."),
  menu_choice: guide("surface-menu", "Active surface is a menu choice. Choose only a supported enabled option consistent with continuing the bounded ordinary run."),
  no_action: guide("surface-no-action", "There is no actionable interaction surface. Do not produce a decision or invoke the model."),
  unsupported: guide("surface-unsupported", "The active interaction protocol is unsupported. Do not produce a decision, infer an action, or invoke the model.")
};
